CREATE TABLE iconic.cls_ecommtrans
(
	customer_id VARCHAR(256) ENCODE lzo,
	days_since_first_order INTEGER ENCODE az64,
	days_since_last_order INTEGER ENCODE az64,
	is_newsletter_subscriber VARCHAR(256) ENCODE lzo,
	orders INTEGER ENCODE az64,
	items INTEGER ENCODE az64,
	cancels INTEGER ENCODE az64,
	returns INTEGER ENCODE az64,
	different_addresses INTEGER ENCODE az64,
	shipping_addresses INTEGER ENCODE az64,
	devices INTEGER ENCODE az64,
	vouchers INTEGER ENCODE az64,
	cc_payments INTEGER ENCODE az64,
	paypal_payments INTEGER ENCODE az64,
	afterpay_payments INTEGER ENCODE az64,
	apple_payments INTEGER ENCODE az64,
	female_items INTEGER ENCODE az64,
	male_items INTEGER ENCODE az64,
	unisex_items INTEGER ENCODE az64,
	wapp_items INTEGER ENCODE az64,
	wftw_items INTEGER ENCODE az64,
	mapp_items INTEGER ENCODE az64,
	wacc_items INTEGER ENCODE az64,
	macc_items INTEGER ENCODE az64,
	mftw_items INTEGER ENCODE az64,
	wspt_items INTEGER ENCODE az64,
	mspt_items INTEGER ENCODE az64,
	curvy_items INTEGER ENCODE az64,
	sacc_items INTEGER ENCODE az64,
	msite_orders INTEGER ENCODE az64,
	desktop_orders INTEGER ENCODE az64,
	android_orders INTEGER ENCODE az64,
	ios_orders INTEGER ENCODE az64,
	other_device_orders INTEGER ENCODE az64,
	work_orders INTEGER ENCODE az64,
	home_orders INTEGER ENCODE az64,
	parcelpoint_orders INTEGER ENCODE az64,
	other_collection_orders INTEGER ENCODE az64,
	average_discount_onoffer DOUBLE PRECISION ENCODE zstd,
	average_discount_used DOUBLE PRECISION ENCODE zstd,
	revenue DOUBLE PRECISION ENCODE zstd,
	inert_ts TIMESTAMP DEFAULT convert_timezone(('UTC'::character varying)::text, ('AUSTRALIA/NSW'::character varying)::text, getdate()) ENCODE az64
)
DISTSTYLE EVEN;
