-- DROP TABLE iconic.stg_ecommtrans;

CREATE TABLE iconic.stg_ecommtrans
(
  afterpay_payments bigint,
  android_orders bigint,
  apple_payments bigint,
  average_discount_onoffer double precision,
  average_discount_used double precision,
  cancels bigint,
  cc_payments bigint,
  coupon_discount_applied double precision,
  curvy_items bigint,
  customer_id text,
  days_since_first_order bigint,
  days_since_last_order bigint,
  desktop_orders bigint,
  devices bigint,
  different_addresses bigint,
  female_items bigint,
  home_orders bigint,
  ios_orders bigint,
  is_newsletter_subscriber text,
  items bigint,
  macc_items bigint,
  male_items bigint,
  mapp_items bigint,
  mftw_items bigint,
  msite_orders bigint,
  mspt_items bigint,
  orders bigint,
  other_collection_orders bigint,
  other_device_orders bigint,
  parcelpoint_orders bigint,
  paypal_payments bigint,
  redpen_discount_used double precision,
  returns bigint,
  revenue double precision,
  sacc_items bigint,
  shipping_addresses bigint,
  unisex_items bigint,
  vouchers bigint,
  wacc_items bigint,
  wapp_items bigint,
  wftw_items bigint,
  work_orders bigint,
  wspt_items bigint
);
