CREATE TABLE public.stg_EcommTrans
(
	sacc_items VARCHAR(256) ENCODE lzo,
	work_orders VARCHAR(256) ENCODE lzo,
	female_items VARCHAR(256) ENCODE lzo,
	is_newsletter_subscriber VARCHAR(256) ENCODE lzo,
	male_items VARCHAR(256) ENCODE lzo,
	afterpay_payments VARCHAR(256) ENCODE lzo,
	msite_orders VARCHAR(256) ENCODE lzo,
	wftw_items VARCHAR(256) ENCODE lzo,
	mapp_items VARCHAR(256) ENCODE lzo,
	orders VARCHAR(256) ENCODE lzo,
	cc_payments VARCHAR(256) ENCODE lzo,
	curvy_items VARCHAR(256) ENCODE lzo,
	paypal_payments VARCHAR(256) ENCODE lzo,
	macc_items VARCHAR(256) ENCODE lzo,
	cancels VARCHAR(256) ENCODE lzo,
	revenue VARCHAR(256) ENCODE lzo,
	returns VARCHAR(256) ENCODE lzo,
	other_collection_orders VARCHAR(256) ENCODE lzo,
	parcelpoint_orders VARCHAR(256) ENCODE lzo,
	customer_id VARCHAR(256) ENCODE lzo,
	android_orders VARCHAR(256) ENCODE lzo,
	days_since_last_order VARCHAR(256) ENCODE lzo,
	vouchers VARCHAR(256) ENCODE lzo,
	average_discount_used VARCHAR(256) ENCODE lzo,
	shipping_addresses VARCHAR(256) ENCODE lzo,
	redpen_discount_used VARCHAR(256) ENCODE lzo,
	mftw_items VARCHAR(256) ENCODE lzo,
	days_since_first_order VARCHAR(256) ENCODE lzo,
	unisex_items VARCHAR(256) ENCODE lzo,
	home_orders VARCHAR(256) ENCODE lzo,
	coupon_discount_applied VARCHAR(256) ENCODE lzo,
	desktop_orders VARCHAR(256) ENCODE lzo,
	ios_orders VARCHAR(256) ENCODE lzo,
	apple_payments VARCHAR(256) ENCODE lzo,
	wspt_items VARCHAR(256) ENCODE lzo,
	wacc_items VARCHAR(256) ENCODE lzo,
	items VARCHAR(256) ENCODE lzo,
	mspt_items VARCHAR(256) ENCODE lzo,
	devices VARCHAR(256) ENCODE lzo,
	different_addresses VARCHAR(256) ENCODE lzo,
	wapp_items VARCHAR(256) ENCODE lzo,
	other_device_orders VARCHAR(256) ENCODE lzo,
	average_discount_onoffer VARCHAR(256) ENCODE lzo
)
DISTSTYLE EVEN;